/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Clases.Pelicula;
import Clases.dbConnection;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anfel
 */
public class MoviesSelector extends javax.swing.JFrame {

    /**
     * Creates new form MoviesSelector
     */
    private int xMouse, yMouse;
    
    public MoviesSelector() {
        initComponents();
        cargarPeliculasDesdeBD();
        this.setSize(800, 600); // o pack() si usas layouts correctamente
        this.setLocationRelativeTo(null); // centra en pantalla
        this.setVisible(true);
    }
    
    
    private void cargarPeliculasDesdeBD() {
        dbConnection dbc = new dbConnection();
        List<Pelicula> peliculas = dbc.obtenerPeliculasDelDia("2025-04-14");

        // Establecer un layout adecuado al contenedor principal
        jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));
        jPanel1.setBackground(Color.WHITE);

        for (Pelicula peli : peliculas) {
            // Panel para cada película
            JPanel panelPeli = new JPanel();
            panelPeli.setLayout(new BoxLayout(panelPeli, BoxLayout.Y_AXIS));
            panelPeli.setBackground(Color.WHITE);
            panelPeli.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1));
            panelPeli.setPreferredSize(new Dimension(160, 280)); // Tamaño fijo del panel

            // Imagen (puedes cambiar el path si luego usas peli.getPosterPath())
            ImageIcon icono = new ImageIcon("src/Images/Star Wars Episodio 3.jpg");
            Image img = icono.getImage().getScaledInstance(150, 220, Image.SCALE_SMOOTH);
            JLabel lblImg = new JLabel(new ImageIcon(img));
            lblImg.setAlignmentX(Component.CENTER_ALIGNMENT);

            // Botón de reserva
            JButton btnReservar = new JButton("Reservar");
            btnReservar.setAlignmentX(Component.CENTER_ALIGNMENT);
            btnReservar.addActionListener(e -> {
                JOptionPane.showMessageDialog(this, "Reservaste: " + peli.getTitulo());
            });

            // Agregar componentes al panel de película
            panelPeli.add(lblImg);
            panelPeli.add(Box.createVerticalStrut(10)); // Espacio entre imagen y botón
            panelPeli.add(btnReservar);

            // Agregar al contenedor principal
            jPanel1.add(panelPeli);
        }

        // Actualizar el contenedor
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
